In [1]:
# Tecnología
import json
import calendar
import pandas as pd
from sparky_bc import Sparky
import datetime as dt
from dateutil.relativedelta import relativedelta

# files lz conection
path_sparky_conf = '/Users/santlond/Documents/sparky_conf.json'
{'ID': "CONTRASEÑA_LZ_EN_SPARKY"}
# Configurar conexión a LZ
with open(path_sparky_conf, 'rb') as JSON_lz_File:
    sp_config = json.loads(JSON_lz_File.read())
    
USER='santlond'
PASS=sp_config['ID']
DSN='IMPALA_PROD'
LOGDIR= 'logs'
# sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp")
sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp", spark_submit="spark3-submit")
# sparky = Sparky(username=USER, password=PASS, dsn=DSN)

helper = sparky.helper

/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-04-10 16:56:59 - [WARNING] - No se encontro la carpeta "/Users/santlond/Documents/ADQUIRENCIA_FERIA_EVA/logs" para guardar los logs

 ____  _____ __  __  ___ _____ _____
|  _ \| ____|  \/  |/ _ \_   _| ____|
| |_) |  _| | |\/| | | | || | |  _|
|  _ <| |___| |  | | |_| || | | |___
|_| \_\_____|_|  |_|\___/ |_| |_____|

 ____  ____   _    ____  _  __
/ ___||  _ \ / \  |  _ \| |/ /
\___ \| |_) / _ \ | |_) | ' /
 ___) |  __/ ___ \|  _ <| . \
|____/|_| /_/   \_\_| \_\_|\_\

## Uso o activo

Un comercio usa adquirencia en un mes específico o mes de análisis cuando:

- Métrica Normal: tienen al menos 1 trx aporbada en ese mes.

- Métrica 5x: tiene al menos 1 trx aprobada en el transucurso de un año, incluyendo el mes de análisis

### Análisis ingestión compras tabla transaccional

In [3]:
# Se deben esperar dos días para que se ingeste la información completa de las transacciones de un día en particular
# Para obtener la información de las compras del día jueves y viernes se debe espear hasta la sgte semana
sql = """
WITH outcome1 AS
  (SELECT YEAR,
          MONTH,
          DAY,
          left(cast(f_trx as string), 10) as f_trx,
          count(*) AS num_compras
   FROM resultados_vspc_medios_de_pago.gsap_m_transaccional
   WHERE YEAR IN (2026)
     AND MONTH IN (3, 4)
     AND DAY BETWEEN 1 AND 31
     and tipo_trx = "Purchase"
   GROUP BY 1,
            2,
            3,
            4
   ORDER BY f_trx DESC, YEAR DESC, MONTH DESC, DAY DESC),
     outcome2 AS
  (SELECT *,
          sum(num_compras) OVER (PARTITION BY f_trx) AS total_compras,
                                sum(num_compras) OVER (PARTITION BY f_trx
                                                       ORDER BY YEAR,
                                                                MONTH,
                                                                DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_compras_cumsum
   FROM outcome1
   ORDER BY f_trx DESC, YEAR DESC, MONTH DESC, DAY DESC)
SELECT *,
       row_number() OVER (PARTITION BY f_trx
                          ORDER BY YEAR,
                                   MONTH,
                                   DAY) AS num_ing,
                         round(num_compras /total_compras, 4) AS prop,
                         round(num_compras_cumsum / total_compras, 4) AS prop_cumsum
FROM outcome2
ORDER BY f_trx DESC,
         YEAR DESC, MONTH DESC, DAY DESC;
"""
df_prueba = helper.obtener_dataframe(sql)

2026-04-09 08:54:42 - [INFO] - Transcurrido: 1775742882, Tiempo de Refresco = 1000

------------------------------------------------------------
  i    tipo    nombre    estado     hora_inicio   duracion
------------------------------------------------------------
 2/2 DATAFRAME        descargando   08:54:42 AM

2026-04-09 08:54:50 - [INFO] - 965 filas, 10 columnas, 00:06.9 consultando, 00:00.5 descargando, 00:00.0 convirtiendo

 2/2 DATAFRAME         finalizado   08:54:42 AM     00:07.7
------------------------------------------------------------

In [4]:
df_prueba.head(40)

,year,month,day,f_trx,num_compras,total_compras,num_compras_cumsum,num_ing,prop,prop_cumsum
0,2026,4,8,2026-04-07,1736284,1736284,1736284,1,1.0000,1.0000
1,2026,4,8,2026-04-06,39500,1781088,1781088,2,0.0222,1.0000
2,2026,4,7,2026-04-06,1741588,1781088,1741588,1,0.9778,0.9778
3,2026,4,8,2026-04-05,68,1911916,1911916,3,0.0000,1.0000
4,2026,4,7,2026-04-05,38388,1911916,1911848,2,0.0201,1.0000
5,2026,4,6,2026-04-05,1873460,1911916,1873460,1,0.9799,0.9799
6,2026,4,8,2026-04-04,10,2176359,2176359,3,0.0000,1.0000
7,2026,4,7,2026-04-04,236,2176359,2176349,2,0.0001,1.0000
8,2026,4,6,2026-04-04,2176113,2176359,2176113,1,0.9999,0.9999
9,2026,4,8,2026-04-03,11,1512843,1512843,3,0.0000,1.0000
10,2026,4,7,2026-04-03,5,1512843,1512832,2,0.0000,1.0000
11,2026,4,6,2026-04-03,1512827,1512843,1512827,1,1.0000,1.0000
12,2026,4,8,2026-04-02,8,1964933,1964933,3,0.0000,1.0000
13,2026,4,7,2026-04-02,1,1964933,1964925,2,0.0000,1.0000
14,2026,4,6,2026-04-02,1964924,1964933,1964924,1,1.0000,1.0000
15,2026,4,8,2026-04-01,10,2469766,2469766,3,0.0000,1.0000
16,2026,4,7,2026-04-01,2,2469766,2469756,2,0.0000,1.0000
17,2026,4,6,2026-04-01,2469754,2469766,2469754,1,1.0000,1.0000
18,2026,4,8,2026-03-31,7,2255464,2255464,3,0.0000,1.0000
19,2026,4,6,2026-03-31,60470,2255464,2255457,2,0.0268,1.0000
20,2026,4,1,2026-03-31,2194987,2255464,2194987,1,0.9732,0.9732
21,2026,4,8,2026-03-30,1,1935719,1935719,5,0.0000,1.0000
22,2026,4,7,2026-03-30,4,1935719,1935718,4,0.0000,1.0000
23,2026,4,6,2026-03-30,88,1935719,1935714,3,0.0000,1.0000
24,2026,4,1,2026-03-30,45760,1935719,1935626,2,0.0236,1.0000
25,2026,3,31,2026-03-30,1889866,1935719,1889866,1,0.9763,0.9763
26,2026,4,7,2026-03-29,1,1935725,1935725,5,0.0000,1.0000
27,2026,4,6,2026-03-29,3,1935725,1935724,4,0.0000,1.0000
28,2026,4,1,2026-03-29,91,1935725,1935721,3,0.0000,1.0000
29,2026,3,31,2026-03-29,42050,1935725,1935630,2,0.0217,1.0000
30,2026,3,30,2026-03-29,1893580,1935725,1893580,1,0.9782,0.9782
31,2026,4,8,2026-03-28,2,2426094,2426094,6,0.0000,1.0000
32,2026,4,6,2026-03-28,2,2426094,2426092,5,0.0000,1.0000
33,2026,4,1,2026-03-28,14,2426094,2426090,4,0.0000,1.0000
34,2026,3,31,2026-03-28,337,2426094,2426076,3,0.0001,1.0000
35,2026,3,30,2026-03-28,2425738,2426094,2425739,2,0.9999,0.9999
36,2026,3,11,2026-03-28,1,2426094,1,1,0.0000,0.0000
37,2026,4,8,2026-03-27,2,2053326,2053326,6,0.0000,1.0000
38,2026,4,7,2026-03-27,1,2053326,2053324,5,0.0000,1.0000
39,2026,4,6,2026-03-27,1,2053326,2053323,4,0.0000,1.0000

## Construcción histórico transacciones

In [ ]:
# Verificar cantidad de registros por partición
# La última ingestión usada 2025-12-11 para obtener las transacciones. # MODIFICAR
sql = """
SELECT YEAR,
       mes,
       dia,
       count(*) AS frec
FROM proceso_vdm.mdo_adquirencia_trxs
WHERE YEAR BETWEEN 2022 AND 2026
  AND mes BETWEEN 1 AND 12
  AND dia BETWEEN 1 AND 31
GROUP BY 1,
         2,
         3
ORDER BY YEAR DESC, mes DESC,
                    dia DESC;
"""
df_prueba = helper.obtener_dataframe(sql)

In [7]:
# Construcción histórico trxs
# Se selecciona el rango de tiempo de las ingestiones a almacenar [Esto para efectos de facilitar la actualización del histórico]
fecha_inicial = '2025-12-14' # MODIFICAR. DEBE SER EL PRIMER DÍA DE INGESTIÓN DE TRANSACCIONES A ALMACENAR O EL SIGUIENTE DÍA DESPUÉS DEL ÚLTIMO EN UNA ACTUALIZACIÓN.
fecha_final = '2026-04-08' # MODIFICAR. DEBE SER EL ÚLTIMO DÍA DE INGESTIÓN DE TRANSACCIONES ALMACENADAS O EL DÍA MÁS RECIENTE EN UNA ACTUALIZACIÓN

fecha_inicial_ts = pd.to_datetime(fecha_inicial)
fecha_final_ts = pd.to_datetime(fecha_final)
fechas = pd.date_range(start=fecha_inicial, end=fecha_final, freq='D')

# # Ir por las particiones del siguiente mes que contendrá las compras de los últimos días del reango de tiempo deseado
# pri_dia_part = fechas[-1] + relativedelta(days=1)
# pri_dia_part = pri_dia_part.date().isoformat() # Primer día de partición para buscar compras del primer día.
# ult_dia_part = fechas[-1] + relativedelta(days=10)
# ult_dia_part = ult_dia_part.date().isoformat()
# fechas_faltantes = pd.date_range(start=pri_dia_part, end=ult_dia_part, freq='D')

# # siguiente_dias = dt.datetime(siguientes_dias.year, siguientes_dias.month, calendar.monthrange(siguientes_dias.year, siguientes_dias.month)[1])
# fechas = fechas.append(fechas_faltantes)

# df_config
df_config = pd.DataFrame({'fechas': fechas})
df_config['year'] = df_config['fechas'].dt.year
df_config['month'] = df_config['fechas'].dt.month
df_config['day'] = df_config['fechas'].dt.day
df_config

        fechas  year  month  day
0   2025-12-14  2025     12   14
1   2025-12-15  2025     12   15
2   2025-12-16  2025     12   16
3   2025-12-17  2025     12   17
4   2025-12-18  2025     12   18
..         ...   ...    ...  ...
111 2026-04-04  2026      4    4
112 2026-04-05  2026      4    5
113 2026-04-06  2026      4    6
114 2026-04-07  2026      4    7
115 2026-04-08  2026      4    8

[116 rows x 4 columns]

In [ ]:
# # Crear tabla que almacenará la información

# sql_drop = """DROP TABLE IF EXISTS proceso_vdm.mdo_adquirencia_trxs;"""
# helper.ejecutar_consulta(sql_drop)

# sql = """
# CREATE TABLE proceso_vdm.mdo_adquirencia_trxs  (
#                 cod_unico VARCHAR,
#                 f_trx STRING,
#                 num_trxs BIGINT,
#                 mnt_total_trxs DECIMAL(38,2),
#                 DIA INT
#                 )
#             PARTITIONED BY 
#             (
#             YEAR INT,
#             MES INT
#             )
# STORED AS PARQUET
# TBLPROPERTIES ('transactional' = 'false');
# """
# helper.ejecutar_consulta(sql)

# sql_compute = """COMPUTE INCREMENTAL STATS proceso_vdm.mdo_adquirencia_trxs;"""

---------------------------------------------------------------------------------------
  i    tipo                 nombre                 estado     hora_inicio   duracion
---------------------------------------------------------------------------------------
 4/4      DROP proceso_vdm.mdo_adquirencia_trxs   finalizado   08:58:39 AM     00:00.9
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
  i    tipo                 nombre                 estado     hora_inicio   duracion
---------------------------------------------------------------------------------------
 5/5    CREATE proceso_vdm.mdo_adquirencia_trxs   finalizado   08:58:40 AM     00:00.7
---------------------------------------------------------------------------------------

In [8]:
# Iterar para obtener las trxs por cliente
for row in df_config.itertuples():
    print('#' * 50)
    print('')
    print('Exrayendo datos de las particiones: ', str(row.year), '-', str(row.month), '-', str(row.day))
    print('')
    print('Obteniendo transacciones adquirencia de los comercios')
    print('')

    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_trxs_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)

    sql = """
    CREATE TABLE proceso.mdo_adquirencia_trxs_temp STORED AS PARQUET AS
    SELECT cod_unico,
       to_date(f_trx) as f_trx,
       count(*) AS num_trxs,
       sum(mnt_total_trx) AS mnt_total_trxs,
        """ + str(row.day) + """ AS DIA,
        """ + str(row.year) + """ AS YEAR,
        """ + str(row.month) + """ AS MES
    FROM resultados_vspc_medios_de_pago.gsap_m_transaccional
    WHERE YEAR = """ + str(row.year) + """
     AND MONTH = """ + str(row.month) + """
     AND DAY = """ + str(row.day) + """
     AND LOWER(TRIM(tipo_trx)) = "purchase"
     AND LOWER(TRIM(estado_trx)) = "cleared"
    GROUP BY 1,
            2;"""
    helper.ejecutar_consulta(sql)

    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando transacciones adquirencia de los comercios')
    print('')

    sql = """
    INSERT INTO proceso_vdm.mdo_adquirencia_trxs PARTITION (YEAR = """ + str(row.year) + """, MES = """ + str(row.month) + """)
    SELECT cod_unico,
           f_trx,
           num_trxs,
           mnt_total_trxs,
           DIA
    FROM proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql)
    print('')

2026-04-09 14:10:04 - [INFO] - Transcurrido: 1775761805, Tiempo de Refresco = 1000

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 14

Obteniendo transacciones adquirencia de los comercios

-----------------------------------------------------------------------------------
  i  tipo              nombre                  estado     hora_inicio   duracion
-----------------------------------------------------------------------------------
 1/1 DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:07 PM     00:01.3
-----------------------------------------------------------------------------------
-------------------------------------------------------------------------------------
  i   tipo               nombre                  estado     hora_inicio   duracion
-------------------------------------------------------------------------------------
 2/2 CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:08 PM     00:01.4
-------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
  i   tipo                nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------
 3/3 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:09 PM     00:01.3
--------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

--------------------------------------------------------------------------------------
  i   tipo                nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------
 4/4  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:10:11 PM     00:01.3
--------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 15

Obteniendo transacciones adquirencia de los comercios

--------------------------------------------------------------------------------------
  i   tipo                nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------
 5/5    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:12 PM     00:01.2
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
  i   tipo                nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------
 6/6  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:14 PM     00:03.4
--------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------
  i   tipo                nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------
 7/7 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:17 PM     00:02.2
--------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

--------------------------------------------------------------------------------------
  i   tipo                nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------
 8/8  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:10:20 PM     00:01.2
--------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 16

Obteniendo transacciones adquirencia de los comercios

--------------------------------------------------------------------------------------
  i   tipo                nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------
 9/9    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:21 PM     00:01.2
--------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 10/10  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:22 PM     00:02.9
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 11/11 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:25 PM     00:01.2
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 12/12  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:10:27 PM     00:01.2
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 17

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 13/13    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:28 PM     00:01.4
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 14/14  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:30 PM     00:02.3
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 15/15 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:32 PM     00:02.2
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 16/16  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:10:35 PM     00:01.6
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 18

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 17/17    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:36 PM     00:01.2
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 18/18  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:38 PM     00:02.2
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 19/19 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:40 PM     00:01.1
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 20/20  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:10:42 PM     00:01.3
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 19

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 21/21    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:43 PM     00:01.2
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 22/22  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:44 PM     00:02.5
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 23/23 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:47 PM     00:01.6
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 24/24  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:10:49 PM     00:01.4
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 20

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 25/25    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:50 PM     00:01.2
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 26/26  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:51 PM     00:01.2
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 27/27 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:53 PM     00:01.3
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 28/28  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:10:54 PM     00:01.4
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 21

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 29/29    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:56 PM     00:02.0
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 30/30  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:58 PM     00:01.2
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 31/31 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:10:59 PM     00:01.6
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 32/32  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:11:01 PM     00:01.3
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 22

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 33/33    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:11:03 PM     00:01.2
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 34/34  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:11:04 PM     00:04.1
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 35/35 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:11:08 PM     00:03.6
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 36/36  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:11:12 PM     00:02.2
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 23

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 37/37    DROP proceso.mdo_adquirencia_trxs_temp   finalizado   02:11:14 PM     00:01.4
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 38/38  CREATE proceso.mdo_adquirencia_trxs_temp   finalizado   02:11:16 PM     00:03.1
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 39/39 COMPUTE proceso.mdo_adquirencia_trxs_temp   finalizado   02:11:19 PM     00:01.6
----------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------
   i    tipo                nombre                  estado     hora_inicio   duracion
----------------------------------------------------------------------------------------
 40/40  INSERT  proceso_vdm.mdo_adquirencia_trxs   finalizado   02:11:21 PM     00:01.7
----------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2025 - 12 - 24

Obteniendo transacciones adquirencia de los comercios

----------------------------------------------------------------------------------------

In [11]:
# Verficar cantidad de registros desde la tabla fuente
sql = """
with outcome as (
SELECT cod_unico,
       to_date(f_trx) as f_trx,
       count(*) AS num_trxs,
       sum(mnt_total_trx) AS mnt_total_trxs
    FROM resultados_vspc_medios_de_pago.gsap_m_transaccional
    WHERE YEAR = 2026
     AND MONTH = 4
     AND DAY = 7
     AND LOWER(TRIM(tipo_trx)) = "purchase"
     AND LOWER(TRIM(estado_trx)) = "cleared"
    GROUP BY 1,
            2
            )
SELECT count(*)
FROM outcome;
"""
helper.obtener_dataframe(sql)

--------------------------------------------------------------------------------------------
    i      tipo                 nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------------
 467/467 DATAFRAME                                    descargando   02:36:11 PM

2026-04-09 14:36:15 - [INFO] - 1 filas, 1 columnas, 00:02.8 consultando, 00:00.8 descargando, 00:00.0 convirtiendo

 467/467 DATAFRAME                                     finalizado   02:36:11 PM     00:04.4
--------------------------------------------------------------------------------------------

   count(*)
0     70244

In [12]:
# Verificar cantidad de registros por partición
# La última ingestión usada 2025-11-14 para obtener las transacciones. # MODIFICAR FECHA
sql = """
SELECT YEAR,
       mes,
       dia,
       count(*) AS frec
FROM proceso_vdm.mdo_adquirencia_trxs
WHERE YEAR BETWEEN 2022 AND 2026
  AND mes BETWEEN 1 AND 12
  AND dia BETWEEN 1 AND 31
GROUP BY 1,
         2,
         3
ORDER BY YEAR DESC, mes DESC, dia DESC;
"""
helper.obtener_dataframe(sql).head(20)

--------------------------------------------------------------------------------------------
    i      tipo                 nombre                  estado     hora_inicio   duracion
--------------------------------------------------------------------------------------------
 468/468 DATAFRAME                                    descargando   02:36:43 PM

2026-04-09 14:36:52 - [INFO] - 1,044 filas, 4 columnas, 00:08.0 consultando, 00:00.8 descargando, 00:00.0 convirtiendo

 468/468 DATAFRAME                                     finalizado   02:36:43 PM     00:09.3
--------------------------------------------------------------------------------------------

    year  mes  dia    frec
0   2026    4    8   70679
1   2026    4    7   70244
2   2026    4    6  256207
3   2026    4    1   74513
4   2026    3   31   72555
5   2026    3   30  186916
6   2026    3   27   72605
7   2026    3   26   70839
8   2026    3   25   68780
9   2026    3   24  233278
10  2026    3   20   72901
11  2026    3   19   71183
12  2026    3   18   70924
13  2026    3   17   70819
14  2026    3   16  187944
15  2026    3   13   71444
16  2026    3   12   71122
17  2026    3   11   69908
18  2026    3   10   69069
19  2026    3    9  184255

## Construcción histórico transacciones por mes

In [13]:

sql_drop = """DROP TABLE IF EXISTS proceso_vdm.mdo_adquirencia_trxs_mes_1 PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso_vdm.mdo_adquirencia_trxs_mes_1 STORED AS PARQUET AS
SELECT cod_unico,
       cast(replace(left(cast(f_trx AS string), 7), '-', '') AS INT) AS periodo_trxs,
       count(*) AS num_trxs,
       sum(mnt_total_trxs) AS mnt_total_trxs
FROM proceso_vdm.mdo_adquirencia_trxs
WHERE YEAR BETWEEN 2022 AND """ + str(df_config.year.values[-1]) + """
AND MES BETWEEN 1 AND 12
GROUP BY 1,
       2;"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso_vdm.mdo_adquirencia_trxs_mes_1;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
    i      tipo                    nombre                    estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 469/469      DROP proceso_vdm.mdo_adquirencia_trxs_mes_1   finalizado   02:37:30 PM     00:01.3
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
    i      tipo                    nombre                    estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 470/470    CREATE proceso_vdm.mdo_adquirencia_trxs_mes_1   finalizado   02:37:31 PM     00:18.8
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
    i      tipo                    nombre                    estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 471/471   COMPUTE proceso_vdm.mdo_adquirencia_trxs_mes_1   finalizado   02:37:50 PM     00:08.9
-------------------------------------------------------------------------------------------------

## Construcción históricos

Se calcula la métrica uso para tres escenarios

- Todos los clientes
- Clientes nuevos
- Clientes viejos

Se dice que un cliente [todos, nuevos o viejos] tiene uso cuando realiza al menos una (1) transaccion en el año corriente. 

Importante tener en cuenta para clientes nuevos. Un cliente que vinculó adquirencia en el año 2024 [nuevo en 2024] y realizó un transacción en el mismo año suma a la métrica, en cambio si ese mismo cliente realiza una transacción en el año 2025 y siguientes no sumará a la métrica de nuevos.

In [2]:
# Tabla que almacenará el número de vinculaciones por mes
# Tabla que almacenará comercios con trxs por periodo
sql_drop = """DROP TABLE IF EXISTS proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist  (
                periodo DOUBLE,
                num_vinc BIGINT,
                tipo_cliente STRING
                )
STORED AS PARQUET
TBLPROPERTIES ('transactional' = 'false');
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist;"""
helper.ejecutar_consulta(sql_compute)

2026-04-10 16:57:09 - [INFO] - Transcurrido: 1775858230, Tiempo de Refresco = 1000

------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 1/1 DROP ..._adquirencia_1_a_1_vinculaciones_hist   finalizado   04:57:11 PM     00:00.6
------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
  i   tipo                   nombre                     estado     hora_inicio   duracion
--------------------------------------------------------------------------------------------
 2/2 CREATE ..._adquirencia_1_a_1_vinculaciones_hist   finalizado   04:57:11 PM     00:00.6
--------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
  i   tipo                    nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 3/3 COMPUTE ..._adquirencia_1_a_1_vinculaciones_hist   finalizado   04:57:12 PM     00:00.7
---------------------------------------------------------------------------------------------

In [3]:
# Tabla que almacenará comercios con trxs por periodo
sql_drop = """DROP TABLE IF EXISTS proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist  (
                codigo_unico VARCHAR,
                periodo DOUBLE,
                num_trxs BIGINT,
                mnt_total_trxs DECIMAL(38,2),
                tipo_cliente STRING
                )
STORED AS PARQUET
TBLPROPERTIES ('transactional' = 'false');
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist;"""
helper.ejecutar_consulta(sql_compute)

---------------------------------------------------------------------------------------------
  i   tipo                    nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 4/4    DROP ...cia_1_a_1_vinculaciones_con_trxs_hist   finalizado   04:57:14 PM     00:00.5
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
  i   tipo                    nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 5/5  CREATE ...cia_1_a_1_vinculaciones_con_trxs_hist   finalizado   04:57:14 PM     00:00.7
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
  i   tipo                    nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 6/6 COMPUTE ...cia_1_a_1_vinculaciones_con_trxs_hist   finalizado   04:57:15 PM     00:01.7
---------------------------------------------------------------------------------------------

In [4]:
# Construcción histórico trxs
# Se selecciona el rango de tiempo de las transacciones a extraer
fecha_inicial = '2022-01-01' # MODIFICAR. INICIO DE UN MES. EN ACTUALIZACIÓN USAR EL SIGUIENTE MES DESPUÉS DEL ÚLTIMO ALMACENADO
fecha_final = '2026-03-31' # MODIFICAR. FIN DE UN MES. EN ACTUALIZACIÓN USAR EL MES RECIENTE CON TRANSACCIONES COMPLETAS
fecha_inicial_ts = pd.to_datetime(fecha_inicial)
fecha_final_ts = pd.to_datetime(fecha_final)
fechas = pd.date_range(start=fecha_inicial, end=fecha_final, freq='M')

# # Ir por las particiones del siguiente mes que contendrá las compras de los últimos días del reango de tiempo deseado
# pri_dia_part = fechas[-1] + relativedelta(days=1)
# pri_dia_part = pri_dia_part.date().isoformat() # Primer día de partición para buscar compras del primer día.
# ult_dia_part = fechas[-1] + relativedelta(days=10)
# ult_dia_part = ult_dia_part.date().isoformat()
# fechas_faltantes = pd.date_range(start=pri_dia_part, end=ult_dia_part, freq='D')

# # siguiente_dias = dt.datetime(siguientes_dias.year, siguientes_dias.month, calendar.monthrange(siguientes_dias.year, siguientes_dias.month)[1])
# fechas = fechas.append(fechas_faltantes)

# df_config
df_config = pd.DataFrame({'fechas': fechas})
df_config['year'] = df_config['fechas'].dt.year
df_config['month'] = df_config['fechas'].dt.month
df_config['day'] = df_config['fechas'].dt.day
df_config['periodo'] = df_config['year'] * 100 + df_config['month']
df_config['periodo_base_year'] = df_config['year'] * 100 + 1
df_config['periodo_viejos'] = df_config['fechas'].apply(lambda x: str(x.year - 1) + '12')
df_config['periodo_sgte_mes'] = df_config['fechas'].apply(lambda x: x + relativedelta(months=1))
df_config['year_sgte_mes'] = df_config['periodo_sgte_mes'].dt.year
df_config['month_sgte_mes'] = df_config['periodo_sgte_mes'].dt.month
df_config['periodo_sgte_mes'] = df_config['periodo_sgte_mes'].apply(lambda x: x.year * 100 + x.month)

# df_config['ult_6_meses_fin'] = df_config['fechas'].apply(lambda x: x - relativedelta(months=5))
# df_config['ult_6_meses_inicio'] = df_config['ult_6_meses_fin'].apply(lambda x: x.replace(day=1))
# df_config['year_ult_6_meses'] = df_config['ult_6_meses_fin'].dt.year
# df_config['month_ult_6_meses'] = df_config['ult_6_meses_fin'].dt.month
# df_config['periodo_ult_6_meses'] = df_config['year_ult_6_meses'] * 100 + df_config['month_ult_6_meses']
df_config

,fechas,year,month,day,periodo,periodo_base_year,periodo_viejos,periodo_sgte_mes,year_sgte_mes,month_sgte_mes
0,2022-01-31,2022,1,31,202201,202201,202112,202202,2022,2
1,2022-02-28,2022,2,28,202202,202201,202112,202203,2022,3
2,2022-03-31,2022,3,31,202203,202201,202112,202204,2022,4
3,2022-04-30,2022,4,30,202204,202201,202112,202205,2022,5
4,2022-05-31,2022,5,31,202205,202201,202112,202206,2022,6
5,2022-06-30,2022,6,30,202206,202201,202112,202207,2022,7
6,2022-07-31,2022,7,31,202207,202201,202112,202208,2022,8
7,2022-08-31,2022,8,31,202208,202201,202112,202209,2022,9
8,2022-09-30,2022,9,30,202209,202201,202112,202210,2022,10
9,2022-10-31,2022,10,31,202210,202201,202112,202211,2022,11
10,2022-11-30,2022,11,30,202211,202201,202112,202212,2022,12
11,2022-12-31,2022,12,31,202212,202201,202112,202301,2023,1
12,2023-01-31,2023,1,31,202301,202301,202212,202302,2023,2
13,2023-02-28,2023,2,28,202302,202301,202212,202303,2023,3
14,2023-03-31,2023,3,31,202303,202301,202212,202304,2023,4
15,2023-04-30,2023,4,30,202304,202301,202212,202305,2023,5
16,2023-05-31,2023,5,31,202305,202301,202212,202306,2023,6
17,2023-06-30,2023,6,30,202306,202301,202212,202307,2023,7
18,2023-07-31,2023,7,31,202307,202301,202212,202308,2023,8
19,2023-08-31,2023,8,31,202308,202301,202212,202309,2023,9
20,2023-09-30,2023,9,30,202309,202301,202212,202310,2023,10
21,2023-10-31,2023,10,31,202310,202301,202212,202311,2023,11
22,2023-11-30,2023,11,30,202311,202301,202212,202312,2023,12
23,2023-12-31,2023,12,31,202312,202301,202212,202401,2024,1
24,2024-01-31,2024,1,31,202401,202401,202312,202402,2024,2
25,2024-02-29,2024,2,29,202402,202401,202312,202403,2024,3
26,2024-03-31,2024,3,31,202403,202401,202312,202404,2024,4
27,2024-04-30,2024,4,30,202404,202401,202312,202405,2024,5
28,2024-05-31,2024,5,31,202405,202401,202312,202406,2024,6
29,2024-06-30,2024,6,30,202406,202401,202312,202407,2024,7
30,2024-07-31,2024,7,31,202407,202401,202312,202408,2024,8
31,2024-08-31,2024,8,31,202408,202401,202312,202409,2024,9
32,2024-09-30,2024,9,30,202409,202401,202312,202410,2024,10
33,2024-10-31,2024,10,31,202410,202401,202312,202411,2024,11
34,2024-11-30,2024,11,30,202411,202401,202312,202412,2024,12
35,2024-12-31,2024,12,31,202412,202401,202312,202501,2025,1
36,2025-01-31,2025,1,31,202501,202501,202412,202502,2025,2
37,2025-02-28,2025,2,28,202502,202501,202412,202503,2025,3
38,2025-03-31,2025,3,31,202503,202501,202412,202504,2025,4
39,2025-04-30,2025,4,30,202504,202501,202412,202505,2025,5
40,2025-05-31,2025,5,31,202505,202501,202412,202506,2025,6
41,2025-06-30,2025,6,30,202506,202501,202412,202507,2025,7
42,2025-07-31,2025,7,31,202507,202501,202412,202508,2025,8
43,2025-08-31,2025,8,31,202508,202501,202412,202509,2025,9
44,2025-09-30,2025,9,30,202509,202501,202412,202510,2025,10
45,2025-10-31,2025,10,31,202510,202501,202412,202511,2025,11
46,2025-11-30,2025,11,30,202511,202501,202412,202512,2025,12
47,2025-12-31,2025,12,31,202512,202501,202412,202601,2026,1
48,2026-01-31,2026,1,31,202601,202601,202512,202602,2026,2
49,2026-02-28,2026,2,28,202602,202601,202512,202603,2026,3
50,2026-03-31,2026,3,31,202603,202601,202512,202604,2026,4

In [5]:
# Leer archivo con el primer día de ingestión de cada mes de la tabla resultados_vspc_medios_de_pago.gsap_m_comercios
# Este archivo lo generá el archivo vinculacion_adquirencia.ipynb
df_primer_dia_ing_gsap_m_comercios = pd.read_excel('main_data/df_primer_dia_ing_vinc.xlsx')
df_primer_dia_ing_gsap_m_comercios.columns = ['year_sgte_mes', 'month_sgte_mes', 'primer_dia_ing_gsap_m_comercios', 'frec']
df_primer_dia_ing_gsap_m_comercios

    year_sgte_mes  month_sgte_mes  primer_dia_ing_gsap_m_comercios    frec
0            2022               1                                1  456338
1            2022               2                                1  460773
2            2022               3                                1  466906
3            2022               4                                1  474754
4            2022               5                                2  481778
5            2022               6                                1  488929
6            2022               7                                1  496027
7            2022               8                                1  502901
8            2022               9                                1  510939
9            2022              10                                3  519318
10           2022              11                                1  527602
11           2022              12                                1  535839
12           2023               1                                2  542404
13           2023               2                                1  548091
14           2023               3                                1  554850
15           2023               4                                3  563040
16           2023               5                                2  569705
17           2023               6                                1  577934
18           2023               7                                4  585501
19           2023               8                                1  593372
20           2023               9                                1  600790
21           2023              10                                1  608259
22           2023              11                                1  615744
23           2023              12                                1  623915
24           2024               1                                2  630383
25           2024               2                                1  635697
26           2024               3                                1  642512
27           2024               4                                1  648212
28           2024               5                                2  653607
29           2024               6                                4  658757
30           2024               7                                2  662896
31           2024               8                                1  667838
32           2024               9                                2  672646
33           2024              10                                1  678111
34           2024              11                                1  682985
35           2024              12                                2  687624
36           2025               1                                2  692058
37           2025               2                                3  695734
38           2025               3                                3  699985
39           2025               4                                1  704456
40           2025               5                                2  709745
41           2025               6                                3  714592
42           2025               7                                1  719324
43           2025               8                                1  724946
44           2025               9                                1  729503
45           2025              10                                1  735188
46           2025              11                                4  741001
47           2025              12                                1  746092
48           2026               1                                2  751556
49           2026               2                                2  755860
50           2026               3                                2  761177
51           2026               4                                1  767416

In [6]:
# Adicionar primer día de ingestión a df_config
df_config = df_config.merge(df_primer_dia_ing_gsap_m_comercios[['year_sgte_mes', 'month_sgte_mes', 'primer_dia_ing_gsap_m_comercios']], on=['year_sgte_mes', 'month_sgte_mes'], how='left')
df_config

,fechas,year,month,day,periodo,periodo_base_year,periodo_viejos,periodo_sgte_mes,year_sgte_mes,month_sgte_mes,primer_dia_ing_gsap_m_comercios
0,2022-01-31,2022,1,31,202201,202201,202112,202202,2022,2,1
1,2022-02-28,2022,2,28,202202,202201,202112,202203,2022,3,1
2,2022-03-31,2022,3,31,202203,202201,202112,202204,2022,4,1
3,2022-04-30,2022,4,30,202204,202201,202112,202205,2022,5,2
4,2022-05-31,2022,5,31,202205,202201,202112,202206,2022,6,1
5,2022-06-30,2022,6,30,202206,202201,202112,202207,2022,7,1
6,2022-07-31,2022,7,31,202207,202201,202112,202208,2022,8,1
7,2022-08-31,2022,8,31,202208,202201,202112,202209,2022,9,1
8,2022-09-30,2022,9,30,202209,202201,202112,202210,2022,10,3
9,2022-10-31,2022,10,31,202210,202201,202112,202211,2022,11,1
10,2022-11-30,2022,11,30,202211,202201,202112,202212,2022,12,1
11,2022-12-31,2022,12,31,202212,202201,202112,202301,2023,1,2
12,2023-01-31,2023,1,31,202301,202301,202212,202302,2023,2,1
13,2023-02-28,2023,2,28,202302,202301,202212,202303,2023,3,1
14,2023-03-31,2023,3,31,202303,202301,202212,202304,2023,4,3
15,2023-04-30,2023,4,30,202304,202301,202212,202305,2023,5,2
16,2023-05-31,2023,5,31,202305,202301,202212,202306,2023,6,1
17,2023-06-30,2023,6,30,202306,202301,202212,202307,2023,7,4
18,2023-07-31,2023,7,31,202307,202301,202212,202308,2023,8,1
19,2023-08-31,2023,8,31,202308,202301,202212,202309,2023,9,1
20,2023-09-30,2023,9,30,202309,202301,202212,202310,2023,10,1
21,2023-10-31,2023,10,31,202310,202301,202212,202311,2023,11,1
22,2023-11-30,2023,11,30,202311,202301,202212,202312,2023,12,1
23,2023-12-31,2023,12,31,202312,202301,202212,202401,2024,1,2
24,2024-01-31,2024,1,31,202401,202401,202312,202402,2024,2,1
25,2024-02-29,2024,2,29,202402,202401,202312,202403,2024,3,1
26,2024-03-31,2024,3,31,202403,202401,202312,202404,2024,4,1
27,2024-04-30,2024,4,30,202404,202401,202312,202405,2024,5,2
28,2024-05-31,2024,5,31,202405,202401,202312,202406,2024,6,4
29,2024-06-30,2024,6,30,202406,202401,202312,202407,2024,7,2
30,2024-07-31,2024,7,31,202407,202401,202312,202408,2024,8,1
31,2024-08-31,2024,8,31,202408,202401,202312,202409,2024,9,2
32,2024-09-30,2024,9,30,202409,202401,202312,202410,2024,10,1
33,2024-10-31,2024,10,31,202410,202401,202312,202411,2024,11,1
34,2024-11-30,2024,11,30,202411,202401,202312,202412,2024,12,2
35,2024-12-31,2024,12,31,202412,202401,202312,202501,2025,1,2
36,2025-01-31,2025,1,31,202501,202501,202412,202502,2025,2,3
37,2025-02-28,2025,2,28,202502,202501,202412,202503,2025,3,3
38,2025-03-31,2025,3,31,202503,202501,202412,202504,2025,4,1
39,2025-04-30,2025,4,30,202504,202501,202412,202505,2025,5,2
40,2025-05-31,2025,5,31,202505,202501,202412,202506,2025,6,3
41,2025-06-30,2025,6,30,202506,202501,202412,202507,2025,7,1
42,2025-07-31,2025,7,31,202507,202501,202412,202508,2025,8,1
43,2025-08-31,2025,8,31,202508,202501,202412,202509,2025,9,1
44,2025-09-30,2025,9,30,202509,202501,202412,202510,2025,10,1
45,2025-10-31,2025,10,31,202510,202501,202412,202511,2025,11,4
46,2025-11-30,2025,11,30,202511,202501,202412,202512,2025,12,1
47,2025-12-31,2025,12,31,202512,202501,202412,202601,2026,1,2
48,2026-01-31,2026,1,31,202601,202601,202512,202602,2026,2,2
49,2026-02-28,2026,2,28,202602,202601,202512,202603,2026,3,2
50,2026-03-31,2026,3,31,202603,202601,202512,202604,2026,4,1

In [7]:
df_config.head(20)

,fechas,year,month,day,periodo,periodo_base_year,periodo_viejos,periodo_sgte_mes,year_sgte_mes,month_sgte_mes,primer_dia_ing_gsap_m_comercios
0,2022-01-31,2022,1,31,202201,202201,202112,202202,2022,2,1
1,2022-02-28,2022,2,28,202202,202201,202112,202203,2022,3,1
2,2022-03-31,2022,3,31,202203,202201,202112,202204,2022,4,1
3,2022-04-30,2022,4,30,202204,202201,202112,202205,2022,5,2
4,2022-05-31,2022,5,31,202205,202201,202112,202206,2022,6,1
5,2022-06-30,2022,6,30,202206,202201,202112,202207,2022,7,1
6,2022-07-31,2022,7,31,202207,202201,202112,202208,2022,8,1
7,2022-08-31,2022,8,31,202208,202201,202112,202209,2022,9,1
8,2022-09-30,2022,9,30,202209,202201,202112,202210,2022,10,3
9,2022-10-31,2022,10,31,202210,202201,202112,202211,2022,11,1
10,2022-11-30,2022,11,30,202211,202201,202112,202212,2022,12,1
11,2022-12-31,2022,12,31,202212,202201,202112,202301,2023,1,2
12,2023-01-31,2023,1,31,202301,202301,202212,202302,2023,2,1
13,2023-02-28,2023,2,28,202302,202301,202212,202303,2023,3,1
14,2023-03-31,2023,3,31,202303,202301,202212,202304,2023,4,3
15,2023-04-30,2023,4,30,202304,202301,202212,202305,2023,5,2
16,2023-05-31,2023,5,31,202305,202301,202212,202306,2023,6,1
17,2023-06-30,2023,6,30,202306,202301,202212,202307,2023,7,4
18,2023-07-31,2023,7,31,202307,202301,202212,202308,2023,8,1
19,2023-08-31,2023,8,31,202308,202301,202212,202309,2023,9,1

In [8]:
for row in df_config.itertuples():
    print('#' * 50)
    print('')
    print('Obteniendo Métrica 5X')
    print('')
    print('Mes de Análisis: ', str(row.year), '-', str(row.month))
    print('')

    print('Viejos')
    print('') 
    print('Obteniendo vinculaciones acumuladas al último mes del año anterior correspondiente al Mes de análisis')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_temp STORED AS PARQUET AS
      SELECT id_comercio as codigo_unico,
             """ + str(row.periodo) + """ AS periodo
      FROM resultados_vspc_medios_de_pago.gsap_m_comercios
      WHERE YEAR = """ + str(row.year_sgte_mes) + """
      AND MONTH = """ + str(row.month_sgte_mes) + """
      AND DAY = """ + str(row.primer_dia_ing_gsap_m_comercios) + """
      AND UPPER(estado_comercio) LIKE 'ACTIV%'
      AND CASE
               WHEN cast(id_comercio_padre AS BIGINT) = cast(nit AS BIGINT) THEN 1
               ELSE 0
            END = 1
      AND year(f_vinculacion_opy)*100 + month(f_vinculacion_opy) <= """ + row.periodo_viejos + """;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando número de vinculados viejos en proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist')
    print('')
    sql = """
    INSERT INTO proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist
    SELECT periodo,
           count(*) AS num_vinc,
           'viejos' as tipo_cliente
    FROM proceso.mdo_adquirencia_vinculaciones_temp
    GROUP BY 1;
    """
    helper.ejecutar_consulta(sql)

    print('')
    print('Obtener las transacciones año base corrido')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_trxs_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_trxs_temp STORED AS PARQUET AS
    select cod_unico,
         sum(num_trxs) as num_trxs,
         sum(mnt_total_trxs) as mnt_total_trxs,
         'viejos' as tipo_cliente
    FROM proceso_vdm.mdo_adquirencia_trxs_mes_1
    WHERE periodo_trxs BETWEEN """ + str(row.periodo_base_year) + """ AND """ + str(row.periodo) + """
    GROUP BY 1;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando en tabla proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist')
    print('')
    
    sql = """
       INSERT INTO proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist
       SELECT a.codigo_unico,
           a.periodo,
           b.num_trxs,
           b.mnt_total_trxs,
           b.tipo_cliente
    FROM proceso.mdo_adquirencia_vinculaciones_temp AS a
    INNER JOIN proceso.mdo_adquirencia_trxs_temp AS b ON a.codigo_unico = b.cod_unico;
    """
    helper.ejecutar_consulta(sql)
    print('')


    print('Nuevos')

    print('') 
    print('Obteniendo vinculaciones correspondiente al Mes de análisis')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_temp_1_new PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_temp_1_new STORED AS PARQUET AS
      SELECT id_comercio as codigo_unico,
             """ + str(row.periodo) + """ AS periodo
      FROM resultados_vspc_medios_de_pago.gsap_m_comercios
      WHERE YEAR = """ + str(row.year_sgte_mes) + """
      AND MONTH = """ + str(row.month_sgte_mes) + """
      AND DAY = """ + str(row.primer_dia_ing_gsap_m_comercios) + """
      AND UPPER(estado_comercio) LIKE 'ACTIV%'
      AND CASE
               WHEN cast(id_comercio_padre AS BIGINT) = cast(nit AS BIGINT) THEN 1
               ELSE 0
            END = 1
      AND year(f_vinculacion_opy)*100 + month(f_vinculacion_opy) = """ + str(row.periodo) + """;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_temp_1_new;"""
    helper.ejecutar_consulta(sql_compute)
    
    print('')
    print('Eliminar los nuevos que ya aparecen en los viejos, se puede presentar múltiples razones, entre ellas: adición de franquicias, la adición de una nueva franquicia genera un nuevo registro en la tabla')
    print('')
    print('Crear tabla con los viejos')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_viejos_temp_new PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_viejos_temp_new STORED AS PARQUET AS
    SELECT codigo_unico, periodo
    FROM proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist
    WHERE tipo_cliente = 'viejos'"""
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_viejos_temp_new;"""
    helper.ejecutar_consulta(sql_compute)
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_temp_new PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_temp_new STORED AS PARQUET AS
    SELECT a.codigo_unico, a.periodo
    FROM proceso.mdo_adquirencia_vinculaciones_temp_1_new AS a
    LEFT ANTI JOIN proceso.mdo_adquirencia_vinculaciones_viejos_temp_new AS b on a.codigo_unico = b.codigo_unico
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_temp_new;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando número de vinculados nuevos en proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist')
    print('')
    sql = """
    INSERT INTO proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist
    SELECT periodo,
           count(*) AS num_vinc,
           'nuevos' as tipo_cliente
    FROM proceso.mdo_adquirencia_vinculaciones_temp_new
    GROUP BY 1;
    """
    helper.ejecutar_consulta(sql)

    print('') 
    print('Obteniendo vinculaciones del año correspondiente, acumuladas hasta el Mes de análisis')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_temp_1 PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_temp_1 STORED AS PARQUET AS
      SELECT id_comercio as codigo_unico,
             """ + str(row.periodo) + """ AS periodo
      FROM resultados_vspc_medios_de_pago.gsap_m_comercios
      WHERE YEAR = """ + str(row.year_sgte_mes) + """
      AND MONTH = """ + str(row.month_sgte_mes) + """
      AND DAY = """ + str(row.primer_dia_ing_gsap_m_comercios) + """
      AND UPPER(estado_comercio) LIKE 'ACTIV%'
      AND CASE
               WHEN cast(id_comercio_padre AS BIGINT) = cast(nit AS BIGINT) THEN 1
               ELSE 0
            END = 1
      AND year(f_vinculacion_opy)*100 + month(f_vinculacion_opy) BETWEEN """ + str(row.periodo_base_year) + """ AND """ + str(row.periodo) + """;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_temp_1;"""
    helper.ejecutar_consulta(sql_compute)
    
    print('')
    print('Eliminar los nuevos que ya aparecen en los viejos, se puede presentar múltiples razones, entre ellas: adición de franquicias, la adición de una nueva franquicia genera un nuevo registro en la tabla')
    print('')
    print('Crear tabla con los viejos')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_viejos_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_viejos_temp STORED AS PARQUET AS
    SELECT codigo_unico, periodo
    FROM proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist
    WHERE tipo_cliente = 'viejos'"""
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_viejos_temp;"""
    helper.ejecutar_consulta(sql_compute)
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_temp STORED AS PARQUET AS
    SELECT a.codigo_unico, a.periodo
    FROM proceso.mdo_adquirencia_vinculaciones_temp_1 AS a
    LEFT ANTI JOIN proceso.mdo_adquirencia_vinculaciones_viejos_temp AS b on a.codigo_unico = b.codigo_unico
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Obtener las transacciones año base corrido')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_trxs_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_trxs_temp STORED AS PARQUET AS
    select cod_unico,
         sum(num_trxs) as num_trxs,
         sum(mnt_total_trxs) as mnt_total_trxs,
         'nuevos' as tipo_cliente
    FROM proceso_vdm.mdo_adquirencia_trxs_mes_1
    WHERE periodo_trxs BETWEEN """ + str(row.periodo_base_year) + """ AND """ + str(row.periodo) + """
    GROUP BY 1;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando en tabla proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist')
    print('')
    
    sql = """
    INSERT INTO proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist
    SELECT a.codigo_unico,
           a.periodo,
           b.num_trxs,
           b.mnt_total_trxs,
           b.tipo_cliente
    FROM proceso.mdo_adquirencia_vinculaciones_temp AS a
    INNER JOIN proceso.mdo_adquirencia_trxs_temp AS b ON a.codigo_unico = b.cod_unico;
    """
    helper.ejecutar_consulta(sql)
    print('')

    print('Todos')
    print('') 
    print('Obteniendo vinculaciones acumuladas hasta el Mes de análisis')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_temp STORED AS PARQUET AS
      SELECT id_comercio as codigo_unico,
             """ + str(row.periodo) + """ AS periodo
      FROM resultados_vspc_medios_de_pago.gsap_m_comercios
      WHERE YEAR = """ + str(row.year_sgte_mes) + """
      AND MONTH = """ + str(row.month_sgte_mes) + """
      AND DAY = """ + str(row.primer_dia_ing_gsap_m_comercios) + """
      AND UPPER(estado_comercio) LIKE 'ACTIV%'
      AND CASE
               WHEN cast(id_comercio_padre AS BIGINT) = cast(nit AS BIGINT) THEN 1
               ELSE 0
            END = 1
      AND year(f_vinculacion_opy)*100 + month(f_vinculacion_opy) <= """ + str(row.periodo) + """;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_vinculaciones_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando número de vinculados (todos) en proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist')
    print('')
    sql = """
    INSERT INTO proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist
    SELECT periodo,
           count(*) AS num_vinc,
           'todos' as tipo_cliente
    FROM proceso.mdo_adquirencia_vinculaciones_temp
    GROUP BY 1;
    """
    helper.ejecutar_consulta(sql)

    print('')
    print('Obtener las transacciones año base corrido')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_trxs_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_trxs_temp STORED AS PARQUET AS
    select cod_unico,
         sum(num_trxs) as num_trxs,
         sum(mnt_total_trxs) as mnt_total_trxs,
         'todos' as tipo_cliente
    FROM proceso_vdm.mdo_adquirencia_trxs_mes_1
    WHERE periodo_trxs BETWEEN """ + str(row.periodo_base_year) + """ AND """ + str(row.periodo) + """
    GROUP BY 1;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando en tabla proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist')
    print('')
    
    sql = """
    INSERT INTO proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist
    SELECT a.codigo_unico,
           a.periodo,
           b.num_trxs,
           b.mnt_total_trxs,
           b.tipo_cliente
    FROM proceso.mdo_adquirencia_vinculaciones_temp AS a
    INNER JOIN proceso.mdo_adquirencia_trxs_temp AS b ON a.codigo_unico = b.cod_unico;
    """
    helper.ejecutar_consulta(sql)
    print('')

##################################################

Obteniendo Métrica 5X

Mes de Análisis:  2022 - 1

Viejos

Obteniendo vinculaciones acumuladas al último mes del año anterior correspondiente al Mes de análisis

---------------------------------------------------------------------------------------------
  i   tipo                    nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 7/7    DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:58:09 PM     00:00.6
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
  i   tipo                    nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 8/8  CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:58:10 PM     00:02.7
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
  i   tipo                    nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 9/9 COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:58:13 PM     00:00.9
---------------------------------------------------------------------------------------------

Insertando número de vinculados viejos en proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 10/10  INSERT ..._adquirencia_1_a_1_vinculaciones_hist   finalizado   04:58:14 PM     00:03.2
-----------------------------------------------------------------------------------------------

Obtener las transacciones año base corrido

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 11/11    DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:58:17 PM     00:00.7
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 12/12  CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:58:18 PM     00:03.8
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 13/13 COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:58:22 PM     00:03.6
-----------------------------------------------------------------------------------------------

Insertando en tabla proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 14/14  INSERT ...cia_1_a_1_vinculaciones_con_trxs_hist   finalizado   04:58:26 PM     00:06.2
-----------------------------------------------------------------------------------------------

Nuevos

Obteniendo vinculaciones correspondiente al Mes de análisis

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 15/15    DROP ..._adquirencia_vinculaciones_temp_1_new   finalizado   04:58:32 PM     00:00.5
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 16/16  CREATE ..._adquirencia_vinculaciones_temp_1_new   finalizado   04:58:33 PM     00:01.5
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 17/17 COMPUTE ..._adquirencia_vinculaciones_temp_1_new   finalizado   04:58:34 PM     00:00.7
-----------------------------------------------------------------------------------------------

Eliminar los nuevos que ya aparecen en los viejos, se puede presentar múltiples razones, entre ellas: adición de franquicias, la adición de una nueva franquicia genera un nuevo registro en la tabla

Crear tabla con los viejos

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 18/18    DROP ...irencia_vinculaciones_viejos_temp_new   finalizado   04:58:35 PM     00:00.8
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 19/19  CREATE ...irencia_vinculaciones_viejos_temp_new   finalizado   04:58:36 PM     00:02.8
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 20/20 COMPUTE ...irencia_vinculaciones_viejos_temp_new   finalizado   04:58:39 PM     00:02.8
-----------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 21/21    DROP ...do_adquirencia_vinculaciones_temp_new   finalizado   04:58:42 PM     00:00.5
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 22/22  CREATE ...do_adquirencia_vinculaciones_temp_new   finalizado   04:58:43 PM     00:04.0
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 23/23 COMPUTE ...do_adquirencia_vinculaciones_temp_new   finalizado   04:58:47 PM     00:03.0
-----------------------------------------------------------------------------------------------

Insertando número de vinculados nuevos en proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 24/24  INSERT ..._adquirencia_1_a_1_vinculaciones_hist   finalizado   04:58:50 PM     00:04.9
-----------------------------------------------------------------------------------------------

Obteniendo vinculaciones del año correspondiente, acumuladas hasta el Mes de análisis

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 25/25    DROP ....mdo_adquirencia_vinculaciones_temp_1   finalizado   04:58:55 PM     00:00.5
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 26/26  CREATE ....mdo_adquirencia_vinculaciones_temp_1   finalizado   04:58:55 PM     00:01.2
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 27/27 COMPUTE ....mdo_adquirencia_vinculaciones_temp_1   finalizado   04:58:57 PM     00:01.1
-----------------------------------------------------------------------------------------------

Eliminar los nuevos que ya aparecen en los viejos, se puede presentar múltiples razones, entre ellas: adición de franquicias, la adición de una nueva franquicia genera un nuevo registro en la tabla

Crear tabla con los viejos

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 28/28    DROP ...adquirencia_vinculaciones_viejos_temp   finalizado   04:58:58 PM     00:00.5
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 29/29  CREATE ...adquirencia_vinculaciones_viejos_temp   finalizado   04:58:59 PM     00:02.8
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 30/30 COMPUTE ...adquirencia_vinculaciones_viejos_temp   finalizado   04:59:02 PM     00:02.6
-----------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 31/31    DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:59:05 PM     00:00.5
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 32/32  CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:59:05 PM     00:02.9
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 33/33 COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:59:08 PM     00:03.3
-----------------------------------------------------------------------------------------------

Obtener las transacciones año base corrido

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 34/34    DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:59:12 PM     00:00.7
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 35/35  CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:59:12 PM     00:03.3
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 36/36 COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:59:16 PM     00:02.4
-----------------------------------------------------------------------------------------------

Insertando en tabla proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 37/37  INSERT ...cia_1_a_1_vinculaciones_con_trxs_hist   finalizado   04:59:18 PM     00:15.4
-----------------------------------------------------------------------------------------------

Todos

Obteniendo vinculaciones acumuladas hasta el Mes de análisis

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 38/38    DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:59:34 PM     00:00.9
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 39/39  CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:59:35 PM     00:04.2
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 40/40 COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:59:39 PM     00:00.7
-----------------------------------------------------------------------------------------------

Insertando número de vinculados (todos) en proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_hist

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 41/41  INSERT ..._adquirencia_1_a_1_vinculaciones_hist   finalizado   04:59:40 PM     00:05.0
-----------------------------------------------------------------------------------------------

Obtener las transacciones año base corrido

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 42/42    DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:59:45 PM     00:03.0
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 43/43  CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:59:48 PM     00:04.4
-----------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------
 44/44 COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:59:53 PM     00:02.5
-----------------------------------------------------------------------------------------------

Insertando en tabla proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist

-----------------------------------------------------------------------------------------------
   i    tipo                    nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------

In [9]:
# Obtener uso por mes
# Número de Vinculaciones
sql = """
SELECT tipo_cliente,
       periodo,
       count(*) AS num_vinc_uso_cumsum_ym
FROM proceso_vdm.mdo_adquirencia_1_a_1_vinculaciones_con_trxs_hist
GROUP BY 1,
         2
ORDER BY periodo DESC, tipo_cliente;
"""
df_prueba = helper.obtener_dataframe(sql)

2026-04-11 08:51:13 - [INFO] - Transcurrido: 51170, Tiempo de Refresco = 1000

-----------------------------------------------------------------------------------------------------
     i       tipo                     nombre                     estado     hora_inicio   duracion
-----------------------------------------------------------------------------------------------------
 1996/1996 DATAFRAME                                           descargando   08:51:13 AM

2026-04-11 08:51:22 - [INFO] - 153 filas, 3 columnas, 00:08.4 consultando, 00:00.3 descargando, 00:00.0 convirtiendo

 1996/1996 DATAFRAME                                            finalizado   08:51:13 AM     00:08.9
-----------------------------------------------------------------------------------------------------

In [10]:
df_prueba.head(50)

   tipo_cliente   periodo  num_vinc_uso_cumsum_ym
0        nuevos  202603.0                    4602
1         todos  202603.0                  110281
2        viejos  202603.0                  105678
3        nuevos  202602.0                    2617
4         todos  202602.0                  106088
5        viejos  202602.0                  103470
6        nuevos  202601.0                    1004
7         todos  202601.0                   99964
8        viejos  202601.0                   98960
9        nuevos  202512.0                   24455
10        todos  202512.0                  137535
11       viejos  202512.0                  113080
12       nuevos  202511.0                   22119
13        todos  202511.0                  134816
14       viejos  202511.0                  112697
15       nuevos  202510.0                   20079
16        todos  202510.0                  132463
17       viejos  202510.0                  112384
18       nuevos  202509.0                   17741
19        todos  202509.0                  129736
20       viejos  202509.0                  111995
21       nuevos  202508.0                   15543
22        todos  202508.0                  127041
23       viejos  202508.0                  111498
24       nuevos  202507.0                   13549
25        todos  202507.0                  124484
26       viejos  202507.0                  110935
27       nuevos  202506.0                   11155
28        todos  202506.0                  121329
29       viejos  202506.0                  110174
30       nuevos  202505.0                    9084
31        todos  202505.0                  118446
32       viejos  202505.0                  109362
33       nuevos  202504.0                    6861
34        todos  202504.0                  114972
35       viejos  202504.0                  108111
36       nuevos  202503.0                    4674
37        todos  202503.0                  111289
38       viejos  202503.0                  106615
39       nuevos  202502.0                    2828
40        todos  202502.0                  106961
41       viejos  202502.0                  104133
42       nuevos  202501.0                    1159
43        todos  202501.0                  100593
44       viejos  202501.0                   99434
45       nuevos  202412.0                   28109
46        todos  202412.0                  150475
47       viejos  202412.0                  122366
48       nuevos  202411.0                   25789
49        todos  202411.0                  147813

In [11]:
df_prueba[df_prueba.tipo_cliente == 'todos']

    tipo_cliente   periodo  num_vinc_uso_cumsum_ym
1          todos  202603.0                  110281
4          todos  202602.0                  106088
7          todos  202601.0                   99964
10         todos  202512.0                  137535
13         todos  202511.0                  134816
16         todos  202510.0                  132463
19         todos  202509.0                  129736
22         todos  202508.0                  127041
25         todos  202507.0                  124484
28         todos  202506.0                  121329
31         todos  202505.0                  118446
34         todos  202504.0                  114972
37         todos  202503.0                  111289
40         todos  202502.0                  106961
43         todos  202501.0                  100593
46         todos  202412.0                  150475
49         todos  202411.0                  147813
52         todos  202410.0                  145129
55         todos  202409.0                  142416
58         todos  202408.0                  139151
61         todos  202407.0                  136320
64         todos  202406.0                  133317
67         todos  202405.0                  130559
70         todos  202404.0                  126883
73         todos  202403.0                  122783
76         todos  202402.0                  117135
79         todos  202401.0                  108323
82         todos  202312.0                  161505
85         todos  202311.0                  157546
88         todos  202310.0                  153331
91         todos  202309.0                  149493
94         todos  202308.0                  145321
97         todos  202307.0                  140889
100        todos  202306.0                  136339
103        todos  202305.0                  131712
106        todos  202304.0                  126957
109        todos  202303.0                  122262
112        todos  202302.0                  115938
115        todos  202301.0                  107477
118        todos  202212.0                  157445
121        todos  202211.0                  153457
124        todos  202210.0                  148966
127        todos  202209.0                  144479
130        todos  202208.0                  139704
133        todos  202207.0                  135132
136        todos  202206.0                  130903
139        todos  202205.0                  126439
142        todos  202204.0                  121448
145        todos  202203.0                  116036
148        todos  202202.0                  109024
151        todos  202201.0                  100138