In [2]:
# Tecnología
import json
import calendar
import pandas as pd
from sparky_bc import Sparky
import datetime as dt
from dateutil.relativedelta import relativedelta

# files lz conection
path_sparky_conf = '/Users/santlond/Documents/sparky_conf.json'

# Configurar conexión a LZ
with open(path_sparky_conf, 'rb') as JSON_lz_File:
    sp_config = json.loads(JSON_lz_File.read())
    
USER='santlond'
PASS=sp_config['ID']
DSN='IMPALA_PROD'
LOGDIR= 'logs'
# sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp")
sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp", spark_submit="spark3-submit")
 
# sparky = Sparky(username=USER, password=PASS, dsn=DSN)

helper = sparky.helper

/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-02-05 14:19:23 - [WARNING] - No se encontro la carpeta "/Users/santlond/Documents/ADQUIRENCIA_FERIA_EVA/logs" para guardar los logs

 ____  _____ __  __  ___ _____ _____
|  _ \| ____|  \/  |/ _ \_   _| ____|
| |_) |  _| | |\/| | | | || | |  _|
|  _ <| |___| |  | | |_| || | | |___
|_| \_\_____|_|  |_|\___/ |_| |_____|

 ____  ____   _    ____  _  __
/ ___||  _ \ / \  |  _ \| |/ /
\___ \| |_) / _ \ | |_) | ' /
 ___) |  __/ ___ \|  _ <| . \
|____/|_| /_/   \_\_| \_\_|\_\

In [21]:
helper.obtener_ultima_ingestion('resultados_vspc_clientes.master_customer_data')

2026-01-16 16:40:42 - [INFO] - Buscando fechas para resultados_vspc_clientes.master_customer_data
2026-01-16 16:40:42 - [INFO] - Transcurrido: 11413, Tiempo de Refresco = 1000
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
2026-01-16 16:40:47 - [INFO] - Finalizo la busqueda, duracion: 00:04.6, resultado: {'year': 2026, 'month': 1, 'day': 15}

{'year': 2026, 'month': 1, 'day': 15}

# Introducción

Se evidencia que los registros en la tabla `resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf` las vinculaciones de adquirencia no comparte registros con la tabla `resultados_wompi.wompi_merchants` que contiene las vinculaciones a wompi

In [22]:
# HASTA QUE AÑO MES SE HAN ACTUALIZADO LAS TRXS
periodo_actual_trxs = '202511'
periodo_actual_trxs

'202511'

# Evolución vinculación aceptación comercios [Adquirencia + Wompi]

## Adquirencia

In [23]:
dict_ult_ing_adqu_vinc = helper.obtener_ultima_ingestion('resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf')
dict_ult_ing_adqu_vinc

2026-01-16 16:40:47 - [INFO] - Buscando fechas para resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
2026-01-16 16:40:47 - [INFO] - Finalizo la busqueda, duracion: 00:00.3, resultado: {'year': 2026, 'month': 1, 'day': 7}

{'year': 2026, 'month': 1, 'day': 7}

In [24]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_hist_vinc_adqu PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_hist_vinc_adqu STORED AS PARQUET AS WITH vinculados AS
  (SELECT codigo_unico,
          min(periodo) AS fecha_ym
   FROM resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
   WHERE YEAR <= """ + str(dict_ult_ing_adqu_vinc['year']) + """
     AND MONTH BETWEEN 1 AND 12
     AND DAY BETWEEN 1 AND 31
     AND periodo IS NOT NULL
   GROUP BY 1),
                                                                                       conteo AS
  (SELECT fecha_ym,
          count(*) AS num_vinc_new,
          cast(left(cast(fecha_ym AS STRING), 4) AS int) AS YEAR,
          cast(right(cast(fecha_ym AS STRING), 2) AS int) AS mes
   FROM vinculados
   GROUP BY 1)
SELECT fecha_ym,
       num_vinc_new,
       sum(num_vinc_new) OVER (PARTITION BY YEAR
                           ORDER BY YEAR,
                                    mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_new_cumsum_ym,
                          'adquirencia' AS producto
FROM conteo
ORDER BY fecha_ym DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_hist_vinc_adqu;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 21/21      DROP ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   04:40:47 PM     00:00.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 22/22    CREATE ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   04:40:47 PM     00:01.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 23/23   COMPUTE ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   04:40:49 PM     00:00.5
-------------------------------------------------------------------------------------------------

## Wompi

In [4]:
dict_ult_ing_wompi_merch = helper.obtener_ultima_ingestion('resultados_wompi.wompi_merchants')
dict_ult_ing_wompi_merch

2026-02-05 14:46:50 - [INFO] - Buscando fechas para resultados_wompi.wompi_merchants
2026-02-05 14:46:50 - [INFO] - Transcurrido: 1639, Tiempo de Refresco = 1000
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
2026-02-05 14:46:51 - [INFO] - Finalizo la busqueda, duracion: 00:00.6, resultado: {'year': 2026, 'month': 2, 'day': 5}

{'year': 2026, 'month': 2, 'day': 5}

In [ ]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_hist_vinc_wompi PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_hist_vinc_wompi STORED AS PARQUET AS
WITH conteo AS (
SELECT CASt(left(cast(creado as string), 6) as int) as fecha_ym, 
       count(*) as num_vinc_new
FROM resultados_wompi.wompi_merchants
WHERE YEAR = """ + str(dict_ult_ing_wompi_merch['year']) + """
  AND MONTH = """ + str(dict_ult_ing_wompi_merch['month']) + """
  AND DAY = """ + str(dict_ult_ing_wompi_merch['day']) + """
        AND modelo = 'Agregador'
        AND activo = 'A'
        AND desembolsos_permitidos = 'Si'
        GROUP BY 1),
        conteo_y_m AS
        (SELECT fecha_ym,
                num_vinc_new,
                cast(left(cast(fecha_ym AS STRING), 4) AS int) AS YEAR,
                cast(right(cast(fecha_ym AS STRING), 2) AS int) AS mes,
                1 AS paracumsum
        FROM conteo)
        SELECT fecha_ym,
        num_vinc_new,
        sum(num_vinc_new) OVER (PARTITION BY YEAR
                                ORDER BY YEAR, mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_new_cumsum_ym,
        sum(num_vinc_new) OVER (PARTITION BY paracumsum
                                ORDER BY fecha_ym) AS num_vinc_new_cumsum,
        'wompi' AS producto
        FROM conteo_y_m
        ORDER BY fecha_ym DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_hist_vinc_wompi;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 24/24      DROP ..._aceptacion_comercios_hist_vinc_wompi   finalizado   04:40:50 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 25/25    CREATE ..._aceptacion_comercios_hist_vinc_wompi   finalizado   04:40:50 PM     00:00.6
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 26/26   COMPUTE ..._aceptacion_comercios_hist_vinc_wompi   finalizado   04:40:51 PM     00:00.7
-------------------------------------------------------------------------------------------------

# Vinculación aceptación comercios

In [27]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_vinc PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_vinc STORED AS PARQUET AS
WITH junte AS
  (SELECT fecha_ym,
          num_vinc_new,
          num_vinc_new_cumsum_ym,
          producto
   FROM proceso.mdo_aceptacion_comercios_hist_vinc_adqu
   UNION ALL SELECT fecha_ym,
                    num_vinc_new,
                    num_vinc_new_cumsum_ym,
                    producto
   FROM proceso.mdo_aceptacion_comercios_hist_vinc_wompi),
     agregado AS
  (SELECT fecha_ym,
          cast(left(cast(fecha_ym AS STRING), 4) AS int) AS YEAR,
          cast(right(cast(fecha_ym AS STRING), 2) AS int) AS mes,
          sum(num_vinc_new) AS num_vinc_new,
          1 AS secuencia2
   FROM junte
   GROUP BY 1,
            2,
            3)
SELECT fecha_ym,
       num_vinc_new,
       sum(num_vinc_new) OVER (PARTITION BY secuencia2 ORDER BY fecha_ym ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_cumsum,
       sum(num_vinc_new) OVER (PARTITION BY YEAR
                           ORDER BY YEAR,
                                    mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_new_cumsum_ym
FROM agregado
ORDER BY fecha_ym DESC;
"""
df_outcome = helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_vinc;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 27/27      DROP    proceso.mdo_aceptacion_comercios_vinc   finalizado   04:40:52 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 28/28    CREATE    proceso.mdo_aceptacion_comercios_vinc   finalizado   04:40:52 PM     00:00.3
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 29/29   COMPUTE    proceso.mdo_aceptacion_comercios_vinc   finalizado   04:40:53 PM     00:00.5
-------------------------------------------------------------------------------------------------

In [28]:
sql = """
SELECT fecha_ym,
       num_vinc_new,
       num_vinc_cumsum,
       num_vinc_new_cumsum_ym
FROM proceso.mdo_aceptacion_comercios_vinc
ORDER BY fecha_ym DESC
"""
df_outcome = helper.obtener_dataframe(sql)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 30/30 DATAFRAME                                            ejecutando   04:40:53 PM

2026-01-16 16:40:54 - [INFO] - 88 filas, 4 columnas, 00:00.5 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

 30/30 DATAFRAME                                            finalizado   04:40:53 PM     00:00.7
-------------------------------------------------------------------------------------------------

In [29]:
df_outcome[40:].head(20)

    fecha_ym  num_vinc_new  num_vinc_cumsum  num_vinc_new_cumsum_ym
40  202209.0          5755           166921                   46334
41  202208.0          6303           161166                   40579
42  202207.0          5110           154863                   34276
43  202206.0          5803           149753                   29166
44  202205.0          5311           143950                   23363
45  202204.0          4498           138639                   18052
46  202203.0          5760           134141                   13554
47  202202.0          4404           128381                    7794
48  202201.0          3390           123977                    3390
49  202112.0          4711           120587                   68234
50  202111.0          7857           115876                   63523
51  202110.0          6261           108019                   55666
52  202109.0          6737           101758                   49405
53  202108.0          3547            95021                   42668
54  202107.0          8171            91474                   39121
55  202106.0          5900            83303                   30950
56  202105.0          4632            77403                   25050
57  202104.0          5421            72771                   20418
58  202103.0          6363            67350                   14997
59  202102.0          5157            60987                    8634

# Uso de vinculados nuevos aceptación comercios

In [30]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_num_vinc_new_uso PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_num_vinc_new_uso STORED AS PARQUET AS
WITH uso_adqui AS
  (SELECT periodo,
          count(*) AS num_vinc_new_uso_adqu
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist
   WHERE producto = 'adqui'
   AND tipo_cliente = 'nuevos'
   GROUP BY 1),
     uso_wompi AS
  (SELECT periodo,
          count(*) AS num_vinc_new_uso_womp
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist
   WHERE producto = 'wompi'
   AND tipo_cliente = 'nuevos'
   GROUP BY 1)
SELECT a.periodo as fecha_ym,
       a.num_vinc_new_uso_adqu + nvl(b.num_vinc_new_uso_womp, 0) AS num_vinc_new_uso_cumsum_ym
FROM uso_adqui AS a
LEFT JOIN uso_wompi AS b ON a.periodo = b.periodo
ORDER BY a.periodo DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_num_vinc_new_uso;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 31/31      DROP ...aceptacion_comercios_num_vinc_new_uso   finalizado   04:40:54 PM     00:00.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 32/32    CREATE ...aceptacion_comercios_num_vinc_new_uso   finalizado   04:40:54 PM     00:05.3
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 33/33   COMPUTE ...aceptacion_comercios_num_vinc_new_uso   finalizado   04:41:00 PM     00:00.9
-------------------------------------------------------------------------------------------------

# Uso de vinculados viejos aceptación comercios

In [31]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_num_vinc_old_uso PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_num_vinc_old_uso STORED AS PARQUET AS
WITH uso_adqui AS
  (SELECT periodo,
          count(*) AS num_vinc_old_uso_adqu
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist
   WHERE producto = 'adqui'
   AND tipo_cliente = 'viejos'
   GROUP BY 1),
     uso_wompi AS
  (SELECT periodo,
          count(*) AS num_vinc_old_uso_womp
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist
   WHERE producto = 'wompi'
   AND tipo_cliente = 'viejos'
   GROUP BY 1)
SELECT a.periodo as fecha_ym,
       a.num_vinc_old_uso_adqu + nvl(b.num_vinc_old_uso_womp, 0) AS num_vinc_old_uso_cumsum_ym
FROM uso_adqui AS a
LEFT JOIN uso_wompi AS b ON a.periodo = b.periodo
ORDER BY a.periodo DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_num_vinc_old_uso;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 34/34      DROP ...aceptacion_comercios_num_vinc_old_uso   finalizado   04:41:01 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 35/35    CREATE ...aceptacion_comercios_num_vinc_old_uso   finalizado   04:41:01 PM     00:11.6
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 36/36   COMPUTE ...aceptacion_comercios_num_vinc_old_uso   finalizado   04:41:13 PM     00:01.2
-------------------------------------------------------------------------------------------------

# Uso de vinculados todos aceptación comercios

In [32]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_num_vinc_all_uso PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_num_vinc_all_uso STORED AS PARQUET AS
WITH uso_adqui AS
  (SELECT periodo,
          count(*) AS num_vinc_all_uso_adqu
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist
   WHERE producto = 'adqui'
   AND tipo_cliente = 'todos'
   GROUP BY 1),
     uso_wompi AS
  (SELECT periodo,
          count(*) AS num_vinc_all_uso_womp
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist
   WHERE producto = 'wompi'
   AND tipo_cliente = 'todos'
   GROUP BY 1)
SELECT a.periodo as fecha_ym,
       a.num_vinc_all_uso_adqu + nvl(b.num_vinc_all_uso_womp, 0) AS num_vinc_all_uso_cumsum_ym
FROM uso_adqui AS a
LEFT JOIN uso_wompi AS b ON a.periodo = b.periodo
ORDER BY a.periodo DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_num_vinc_all_uso;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 37/37      DROP ...aceptacion_comercios_num_vinc_all_uso   finalizado   04:41:14 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 38/38    CREATE ...aceptacion_comercios_num_vinc_all_uso   finalizado   04:41:14 PM     00:10.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 39/39   COMPUTE ...aceptacion_comercios_num_vinc_all_uso   finalizado   04:41:25 PM     00:01.3
-------------------------------------------------------------------------------------------------

# Tabla resultado

In [33]:
sql = """
WITH outcome1 AS
  (SELECT a.fecha_ym,
          a.num_vinc_new,
          a.num_vinc_cumsum,
          a.num_vinc_new_cumsum_ym,
          nvl(b.num_vinc_new_uso_cumsum_ym, 0) AS num_vinc_new_uso_cumsum_ym,
          round(nvl(b.num_vinc_new_uso_cumsum_ym, 0)/a.num_vinc_new_cumsum_ym, 4) AS num_vinc_new_prop_uso,
          nvl(c.num_vinc_old_uso_cumsum_ym, 0) AS num_vinc_old_uso_cumsum_ym,
          nvl(d.num_vinc_all_uso_cumsum_ym, 0) AS num_vinc_all_uso_cumsum_ym,
          round(nvl(d.num_vinc_all_uso_cumsum_ym, 0)/a.num_vinc_cumsum, 4) AS num_vinc_all_prop_uso,
          left(cast(a.fecha_ym AS string), 4) AS YEAR,
          right(cast(a.fecha_ym AS string), 2) AS mes
   FROM proceso.mdo_aceptacion_comercios_vinc AS a
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_new_uso AS b ON a.fecha_ym = b.fecha_ym
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_old_uso AS c ON a.fecha_ym = c.fecha_ym
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_all_uso AS d ON a.fecha_ym = d.fecha_ym),
     outcome2 AS
  (SELECT fecha_ym,
          num_vinc_cumsum AS num_vinc_old,
          cast(cast(YEAR AS int) + 1 AS string) AS YEAR
   FROM outcome1
   WHERE mes = '12')
SELECT a.fecha_ym,
       CONCAT(a.YEAR, '/', a.mes, '/', '01') AS fecha_ym2,
       a.num_vinc_new,
       a.num_vinc_new_cumsum_ym,
       a.num_vinc_new_uso_cumsum_ym,
       a.num_vinc_new_prop_uso,
       b.num_vinc_old,
       a.num_vinc_old_uso_cumsum_ym,
       round(a.num_vinc_old_uso_cumsum_ym/b.num_vinc_old, 4) AS num_vinc_old_prop_uso,
       a.num_vinc_cumsum,
       a.num_vinc_all_uso_cumsum_ym,
       a.num_vinc_all_prop_uso
FROM outcome1 AS a
LEFT JOIN outcome2 AS b ON a.year = b.year
WHERE a.fecha_ym BETWEEN 202201 AND 202511
ORDER BY a.fecha_ym DESC;
"""
# print(sql)
df_outcome = helper.obtener_dataframe(sql)
df_outcome

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 40/40 DATAFRAME                                            ejecutando   04:41:26 PM

2026-01-16 16:41:27 - [INFO] - 47 filas, 12 columnas, 00:00.4 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

 40/40 DATAFRAME                                            finalizado   04:41:26 PM     00:00.6
-------------------------------------------------------------------------------------------------

,fecha_ym,fecha_ym2,num_vinc_new,num_vinc_new_cumsum_ym,num_vinc_new_uso_cumsum_ym,num_vinc_new_prop_uso,num_vinc_old,num_vinc_old_uso_cumsum_ym,num_vinc_old_prop_uso,num_vinc_cumsum,num_vinc_all_uso_cumsum_ym,num_vinc_all_prop_uso
0,202511.0,2025/11/01,14967,98583,38823,0.3938,309628,103274,0.3335,408211,142097,0.3481
1,202510.0,2025/10/01,16147,83616,34180,0.4088,309628,102731,0.3318,393244,136911,0.3482
2,202509.0,2025/09/01,18340,67469,29340,0.4349,309628,102090,0.3297,377097,131430,0.3485
3,202508.0,2025/08/01,10610,49129,22020,0.4482,309628,101310,0.3272,358757,123330,0.3438
4,202507.0,2025/07/01,7872,38519,19882,0.5162,309628,100437,0.3244,348147,120319,0.3456
5,202506.0,2025/06/01,6189,30647,15970,0.5211,309628,99408,0.3211,340275,115378,0.3391
6,202505.0,2025/05/01,6326,24458,12905,0.5276,309628,98241,0.3173,334086,111146,0.3327
7,202504.0,2025/04/01,5101,18132,9492,0.5235,309628,96434,0.3115,327760,105926,0.3232
8,202503.0,2025/03/01,4730,13031,6541,0.5020,309628,94424,0.3050,322659,100965,0.3129
9,202502.0,2025/02/01,4296,8301,3989,0.4805,309628,91308,0.2949,317929,107771,0.3390
10,202501.0,2025/01/01,4005,4005,1619,0.4042,309628,85796,0.2771,313633,87415,0.2787
11,202412.0,2024/12/01,4503,63018,39667,0.6295,246610,100526,0.4076,309628,140193,0.4528
12,202411.0,2024/11/01,5218,58515,35808,0.6119,246610,100092,0.4059,305125,135900,0.4454
13,202410.0,2024/10/01,5726,53297,32221,0.6046,246610,99571,0.4038,299907,131792,0.4394
14,202409.0,2024/09/01,6022,47571,28756,0.6045,246610,98985,0.4014,294181,127741,0.4342
15,202408.0,2024/08/01,5239,41549,24609,0.5923,246610,98359,0.3988,288159,122968,0.4267
16,202407.0,2024/07/01,5576,36310,21322,0.5872,246610,97578,0.3957,282920,118900,0.4203
17,202406.0,2024/06/01,4629,30734,17642,0.5740,246610,96580,0.3916,277344,114222,0.4118
18,202405.0,2024/05/01,5386,26105,14993,0.5743,246610,95515,0.3873,272715,110508,0.4052
19,202404.0,2024/04/01,5339,20719,11875,0.5731,246610,93968,0.3810,267329,105843,0.3959
20,202403.0,2024/03/01,5136,15380,8816,0.5732,246610,91919,0.3727,261990,100735,0.3845
21,202402.0,2024/02/01,5863,10244,5213,0.5089,246610,89032,0.3610,256854,94245,0.3669
22,202401.0,2024/01/01,4381,4381,1531,0.3495,246610,83314,0.3378,250991,84845,0.3380
23,202312.0,2023/12/01,5406,63508,47052,0.7409,183102,88413,0.4829,246610,135465,0.5493
24,202311.0,2023/11/01,6386,58102,42543,0.7322,183102,88034,0.4808,241204,130577,0.5414
25,202310.0,2023/10/01,5489,51716,37858,0.7320,183102,87603,0.4784,234818,125461,0.5343
26,202309.0,2023/09/01,5611,46227,33878,0.7329,183102,87123,0.4758,229329,121001,0.5276
27,202308.0,2023/08/01,5565,40616,29498,0.7263,183102,86565,0.4728,223718,116063,0.5188
28,202307.0,2023/07/01,5982,35051,21785,0.6215,183102,85840,0.4688,218153,107625,0.4933
29,202306.0,2023/06/01,4772,29069,20748,0.7138,183102,84976,0.4641,212171,105724,0.4983
30,202305.0,2023/05/01,5651,24297,16469,0.6778,183102,83936,0.4584,207399,100405,0.4841
31,202304.0,2023/04/01,4519,18646,12444,0.6674,183102,82677,0.4515,201748,95121,0.4715
32,202303.0,2023/03/01,5293,14127,8955,0.6339,183102,80976,0.4422,197229,89931,0.4560
33,202302.0,2023/02/01,4713,8834,4882,0.5526,183102,78265,0.4274,191936,83147,0.4332
34,202301.0,2023/01/01,4121,4121,1564,0.3795,183102,73590,0.4019,187223,75154,0.4014
35,202212.0,2022/12/01,4453,62515,0,0.0000,120587,0,0.0000,183102,0,0.0000
36,202211.0,2022/11/01,5793,58062,0,0.0000,120587,0,0.0000,178649,0,0.0000
37,202210.0,2022/10/01,5935,52269,0,0.0000,120587,0,0.0000,172856,0,0.0000
38,202209.0,2022/09/01,5755,46334,0,0.0000,120587,0,0.0000,166921,0,0.0000
39,202208.0,2022/08/01,6303,40579,0,0.0000,120587,0,0.0000,161166,0,0.0000
40,202207.0,2022/07/01,5110,34276,0,0.0000,120587,0,0.0000,154863,0,0.0000
41,202206.0,2022/06/01,5803,29166,0,0.0000,120587,0,0.0000,149753,0,0.0000
42,202205.0,2022/05/01,5311,23363,0,0.0000,120587,0,0.0000,143950,0,0.0000
43,202204.0,2022/04/01,4498,18052,0,0.0000,120587,0,0.0000,138639,0,0.0000
44,202203.0,2022/03/01,5760,13554,0,0.0000,120587,0,0.0000,134141,0,0.0000
45,202202.0,2022/02/01,4404,7794,0,0.0000,120587,0,0.0000,128381,0,0.0000
46,202201.0,2022/01/01,3390,3390,0,0.0000,120587,0,0.0000,123977,0,0.0000

In [ ]:
sql = """
WITH outcome1 AS
  (SELECT a.fecha_ym,
          a.num_vinc_new,
          a.num_vinc_cumsum,
          a.num_vinc_new_cumsum_ym,
          nvl(b.num_vinc_new_uso_cumsum_ym, 0) AS num_vinc_new_uso_cumsum_ym,
          round(nvl(b.num_vinc_new_uso_cumsum_ym, 0)/a.num_vinc_new_cumsum_ym, 4) AS num_vinc_new_prop_uso,
          nvl(c.num_vinc_old_uso_cumsum_ym, 0) AS num_vinc_old_uso_cumsum_ym,
          nvl(d.num_vinc_all_uso_cumsum_ym, 0) AS num_vinc_all_uso_cumsum_ym,
          round(nvl(d.num_vinc_all_uso_cumsum_ym, 0)/a.num_vinc_cumsum, 4) AS num_vinc_all_prop_uso,
          left(cast(a.fecha_ym AS string), 4) AS YEAR,
          right(cast(a.fecha_ym AS string), 2) AS mes
   FROM proceso.mdo_aceptacion_comercios_vinc AS a
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_new_uso AS b ON a.fecha_ym = b.fecha_ym
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_old_uso AS c ON a.fecha_ym = c.fecha_ym
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_all_uso AS d ON a.fecha_ym = d.fecha_ym),
     outcome2 AS
  (SELECT fecha_ym,
          num_vinc_cumsum AS num_vinc_old,
          cast(cast(YEAR AS int) + 1 AS string) AS YEAR
   FROM outcome1
   WHERE mes = '12')
SELECT a.fecha_ym,
       CONCAT(a.YEAR, '/', a.mes, '/', '01') AS fecha_ym2,
       a.num_vinc_new,
       a.num_vinc_new_cumsum_ym,
       a.num_vinc_new_uso_cumsum_ym,
       a.num_vinc_new_prop_uso,
       b.num_vinc_old,
       a.num_vinc_old_uso_cumsum_ym,
       round(a.num_vinc_old_uso_cumsum_ym/b.num_vinc_old, 4) AS num_vinc_old_prop_uso,
       a.num_vinc_cumsum,
       a.num_vinc_all_uso_cumsum_ym,
       a.num_vinc_all_prop_uso
FROM outcome1 AS a
LEFT JOIN outcome2 AS b ON a.year = b.year
WHERE a.fecha_ym BETWEEN 202201 AND 202511
ORDER BY a.fecha_ym DESC;
"""
# print(sql)
df_outcome = helper.obtener_dataframe(sql)
df_outcome

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 100/100 DATAFRAME                                           descargando   12:14:47 AM

2025-12-12 00:14:48 - [INFO] - 47 filas, 12 columnas, 00:00.6 consultando, 00:00.2 descargando, 00:00.0 convirtiendo

 100/100 DATAFRAME                                            finalizado   12:14:47 AM     00:00.9
---------------------------------------------------------------------------------------------------

,fecha_ym,fecha_ym2,num_vinc_new,num_vinc_new_cumsum_ym,num_vinc_new_uso_cumsum_ym,num_vinc_new_prop_uso,num_vinc_old,num_vinc_old_uso_cumsum_ym,num_vinc_old_prop_uso,num_vinc_cumsum,num_vinc_all_uso_cumsum_ym,num_vinc_all_prop_uso
0,202511.0,2025/11/01,14983,98681,37253,0.3775,309667,96086,0.3103,408348,133339,0.3265
1,202510.0,2025/10/01,16180,83698,32665,0.3903,309667,95557,0.3086,393365,128222,0.3260
2,202509.0,2025/09/01,18355,67518,27900,0.4132,309667,94927,0.3065,377185,122827,0.3256
3,202508.0,2025/08/01,10621,49163,22995,0.4677,309667,94168,0.3041,358830,117163,0.3265
4,202507.0,2025/07/01,7876,38542,18936,0.4913,309667,93317,0.3013,348209,112253,0.3224
5,202506.0,2025/06/01,6191,30666,15268,0.4979,309667,92331,0.2982,340333,107599,0.3162
6,202505.0,2025/05/01,6337,24475,12327,0.5037,309667,91225,0.2946,334142,103552,0.3099
7,202504.0,2025/04/01,5104,18138,9031,0.4979,309667,89479,0.2890,327805,98510,0.3005
8,202503.0,2025/03/01,4731,13034,6196,0.4754,309667,87526,0.2826,322701,93722,0.2904
9,202502.0,2025/02/01,4296,8303,3760,0.4528,309667,84511,0.2729,317970,88271,0.2776
10,202501.0,2025/01/01,4007,4007,1532,0.3823,309667,79147,0.2556,313674,80679,0.2572
11,202412.0,2024/12/01,4503,63035,37912,0.6014,246632,93859,0.3806,309667,131771,0.4255
12,202411.0,2024/11/01,5221,58532,34340,0.5867,246632,93436,0.3788,305164,127965,0.4193
13,202410.0,2024/10/01,5728,53311,31092,0.5832,246632,92930,0.3768,299943,124022,0.4135
14,202409.0,2024/09/01,6023,47583,27744,0.5831,246632,92347,0.3744,294215,119348,0.4056
15,202408.0,2024/08/01,5240,41560,24050,0.5787,246632,91732,0.3719,288192,115782,0.4018
16,202407.0,2024/07/01,5580,36320,20987,0.5778,246632,90968,0.3688,282952,111955,0.3957
17,202406.0,2024/06/01,4632,30740,17724,0.5766,246632,90017,0.3650,277372,107741,0.3884
18,202405.0,2024/05/01,5386,26108,15160,0.5807,246632,88979,0.3608,272740,104139,0.3818
19,202404.0,2024/04/01,5339,20722,12131,0.5854,246632,87489,0.3547,267354,99620,0.3726
20,202403.0,2024/03/01,5138,15383,9282,0.6034,246632,85515,0.3467,262015,94797,0.3618
21,202402.0,2024/02/01,5864,10245,5779,0.5641,246632,82730,0.3354,256877,88509,0.3446
22,202401.0,2024/01/01,4381,4381,2221,0.5070,246632,77206,0.3130,251013,79427,0.3164
23,202312.0,2023/12/01,5406,63516,46615,0.7339,183116,82060,0.4481,246632,128675,0.5217
24,202311.0,2023/11/01,6386,58110,42216,0.7265,183116,81695,0.4461,241226,123911,0.5137
25,202310.0,2023/10/01,5490,51724,37489,0.7248,183116,81276,0.4438,234840,119016,0.5068
26,202309.0,2023/09/01,5612,46234,33812,0.7313,183116,80811,0.4413,229350,114623,0.4998
27,202308.0,2023/08/01,5565,40622,29574,0.7280,183116,80267,0.4383,223738,109841,0.4909
28,202307.0,2023/07/01,5983,35057,25249,0.7202,183116,79564,0.4345,218173,104813,0.4804
29,202306.0,2023/06/01,4774,29074,21000,0.7223,183116,78729,0.4299,212190,99729,0.4700
30,202305.0,2023/05/01,5653,24300,16902,0.6956,183116,77767,0.4247,207416,94669,0.4564
31,202304.0,2023/04/01,4520,18647,12954,0.6947,183116,76566,0.4181,201763,89520,0.4437
32,202303.0,2023/03/01,5293,14127,9541,0.6754,183116,74923,0.4092,197243,84464,0.4282
33,202302.0,2023/02/01,4713,8834,5587,0.6324,183116,72328,0.3950,191950,77915,0.4059
34,202301.0,2023/01/01,4121,4121,2201,0.5341,183116,67875,0.3707,187237,70076,0.3743
35,202212.0,2022/12/01,4453,62517,48563,0.7768,120599,62456,0.5179,183116,111019,0.6063
36,202211.0,2022/11/01,5794,58064,44504,0.7665,120599,62156,0.5154,178663,106660,0.5970
37,202210.0,2022/10/01,5935,52270,39844,0.7623,120599,61790,0.5124,172869,101634,0.5879
38,202209.0,2022/09/01,5755,46335,35168,0.7590,120599,61437,0.5094,166934,96605,0.5787
39,202208.0,2022/08/01,6303,40580,30401,0.7492,120599,61020,0.5060,161179,91421,0.5672
40,202207.0,2022/07/01,5110,34277,25640,0.7480,120599,60538,0.5020,154876,86178,0.5564
41,202206.0,2022/06/01,5804,29167,21596,0.7404,120599,60009,0.4976,149766,81605,0.5449
42,202205.0,2022/05/01,5311,23363,16995,0.7274,120599,59244,0.4912,143962,76239,0.5296
43,202204.0,2022/04/01,4498,18052,12985,0.7193,120599,58226,0.4828,138651,71211,0.5136
44,202203.0,2022/03/01,5760,13554,9245,0.6821,120599,56949,0.4722,134153,66194,0.4934
45,202202.0,2022/02/01,4404,7794,4978,0.6387,120599,54729,0.4538,128393,59707,0.4650
46,202201.0,2022/01/01,3390,3390,1778,0.5245,120599,50901,0.4221,123989,52679,0.4249

In [ ]:
df_outcome.to_excel('main_data/evolucion_vinculacion_y_uso_adquirencia_y_wompi.xlsx')

# Eliminación tablas proceso.

In [3]:
# Eliminación tablas proceso.
tablas_borrar = ['proceso.mdo_aceptacion_comercios_hist_vinc_adqu', 'proceso.mdo_aceptacion_comercios_hist_vinc_wompi', 'proceso.mdo_aceptacion_comercios_vinc', 'proceso.mdo_aceptacion_comercios_num_vinc_new_uso', 'proceso.mdo_aceptacion_comercios_num_vinc_old_uso', 'proceso.mdo_aceptacion_comercios_num_vinc_all_uso']
for tabla in tablas_borrar:
    sql_drop = f"""DROP TABLE IF EXISTS {tabla} PURGE;"""
    helper.ejecutar_consulta(sql_drop)

2026-02-05 14:19:30 - [INFO] - Transcurrido: 1770319170, Tiempo de Refresco = 1000

------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 1/1 DROP ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   02:19:30 PM     00:00.1
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 2/2 DROP ..._aceptacion_comercios_hist_vinc_wompi   finalizado   02:19:30 PM     00:00.1
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 3/3 DROP    proceso.mdo_aceptacion_comercios_vinc   finalizado   02:19:30 PM     00:00.0
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 4/4 DROP ...aceptacion_comercios_num_vinc_new_uso   finalizado   02:19:30 PM     00:00.0
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 5/5 DROP ...aceptacion_comercios_num_vinc_old_uso   finalizado   02:19:31 PM     00:00.0
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 6/6 DROP ...aceptacion_comercios_num_vinc_all_uso   finalizado   02:19:31 PM     00:00.0
------------------------------------------------------------------------------------------